### ISSUE TITLE
Update TXN_DATA udpate

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/linea-arithmetization#656]
Implement the TXN_DATA update

**Spec** https://github.com/Consensys/zkevm-spec/pull/364
**Corset** https://github.com/Consensys/zkevm-constraints/issues/140

**Comment by letypequividelespoubelles** [comment]
and https://github.com/Consensys/linea-spec/issues/421
and https://github.com/Consensys/linea-spec/issues/409
